<?php

return [
    'Volteador de Vagones/Contactos Clientes/Luis Hernández/Cédula.pdf',
    'Volteador de Vagones/Contactos Clientes/Luis Hernández/RIF.pdf',
    'Volteador de Vagones/Contactos Clientes/Luis Hernández/Detalle de Contacto/Archivos Específicos/Historial de Llamadas.pdf',
    'Volteador de Vagones/Contactos Clientes/Carlos Pereira/Cédula.pdf',
    'Volteador de Vagones/Contactos Clientes/Carlos Pereira/RIF.pdf',
    'Volteador de Vagones/Contactos Clientes/Carlos Pereira/Algo de Carlos.pdf',
    'Volteador de Vagones/Contactos Clientes/Nuevo Contacto Julio/Datos contacto.pdf',
    'Volteador de Vagones/Contactos Clientes/Nuevo Contacto Julio/Correo Inicial.pdf',
    'Volteador de Vagones/Contactos Proveedor/Proveedor A/Cotizacion General.pdf',
    'Volteador de Vagones/Contactos Proveedor/Proveedor A/Documentación Legal/Contratos/Contrato Marco Vigente.pdf',
    'Volteador de Vagones/Contactos Proveedor/Proveedor D/Referencia Comercial.pdf',
    'Volteador de Vagones/Descripcion General/Ficha Tecnica Vagon.pdf',
    'Volteador de Vagones/Descripcion General/Resumen Ejecutivo.pdf',
    'Volteador de Vagones/Descripcion General/Diagrama/Operativo/Detallado/Diagrama de Flujo Operativo.pdf',
    'Volteador de Vagones/Especificaciones Tecnicas/Especificacion 001.pdf',
    'Volteador de Vagones/Especificaciones Tecnicas/Normativa/Certificaciones/Regulaciones Vigentes/Normativa Aplicable.pdf',
    'Volteador de Vagones/Fotos/Vistas Generales/Año 2023/Alta Resolución/Foto Vagon Frente.pdf',
    'Volteador de Vagones/Fotos/Foto Vagon Interior.pdf',
    'Volteador de Vagones/Fotos/Foto Cabina.pdf',
    'Volteador de Vagones/Manuales/Manual Operacion V1.pdf',
    'Volteador de Vagones/Manuales/Mantenimiento/Procedimientos/Instrucciones Detalladas/Manual Mantenimiento Preventivo.pdf',
    'Volteador de Vagones/Ofertas/Oferta Mantenimiento 2024.pdf',
    'Volteador de Vagones/Ofertas/Propuestas/Adicionales/En Aprobacion/Propuesta Servicio Adicional.pdf',
    'Volteador de Vagones/Planos/Estructural/Versión Final/Original/Plano Estructura Principal.pdf',
    'Volteador de Vagones/Planos/Plano Sistemas Hidraulicos.pdf',
    'Volteador de Vagones/Proveedores/Proveedor A/Datos Proveedor A.pdf',
    'Volteador de Vagones/Proveedores/Proveedor A/Contactos/Key Account/Tarjeta de Presentación.pdf',
    'Volteador de Vagones/Proveedores/Proveedor D/Datos Proveedor D.pdf',
    'Volteador de Vagones/Proyectos/Modernizacion 2025/Fase 1/Documentos de Inicio/Proyecto Modernizacion 2025.pdf',
    'Volteador de Vagones/Proyectos/Estudio de Viabilidad 2023.pdf',
    'Volteador de Vagones/Reportes/Inspeccion/Inicial/Resumen/Reporte Inspeccion Inicio.pdf',
    'Volteador de Vagones/Reportes/Reporte Consolidado Mensual.pdf',
    'Volteador de Vagones/Repuestos/Rueda Bogie XV/Planos/Versión Actual/Plano Bogie XV.pdf',
    'Volteador de Vagones/Repuestos/Rueda Bogie XV/Planos/Versión Actual/Plano Bogie XV.pdf',
    'Volteador de Vagones/Repuestos/Rueda Bogie XV/Fotos/Inspeccion Detallada/Foto Rueda Dañada.pdf',
    'Volteador de Vagones/Repuestos/Rueda Bogie XV/Manuales/Guía de Instalación/Manual Repuesto Rueda.pdf',
    'Volteador de Vagones/Repuestos/Freno Neumático/Especificaciones Tecnicas/Detalles Neumáticos/ET Freno Neumatico.pdf',
    'Volteador de Vagones/Repuestos/Freno Neumático/Especificaciones Tecnicas/Detalles Neumáticos/ET Freno Neumatico.pdf',
    'Volteador de Vagones/Repuestos/Freno Neumático/Ofertas/Suministro Anual/Oferta Suministro Filtros.pdf',
    'Volteador de Vagones/Repuestos/Stock General/Reportes/Inventario/Primer Trimestre/Reporte Inventario Repuestos Q1.pdf',
    'Bomba Industrial/Contactos Clientes/Carlos Pereira/Cédula.pdf',
    'Bomba Industrial/Contactos Clientes/Carlos Pereira/RIF.pdf',
    'Bomba Industrial/Contactos Clientes/Carlos Pereira/Archivos Faltantes/Pendiente de Entrega/Algo faltante a Carlos antes.pdf',
    'Bomba Industrial/Contactos Clientes/Miguel Díaz/Completamente.pdf',
    'Bomba Industrial/Contactos Clientes/Miguel Díaz/Distinto.pdf',
    'Bomba Industrial/Contactos Clientes/Miguel Díaz/Correos recibidos/Archivados/Correo archivado de Miguel.pdf',
    'Bomba Industrial/Contactos Clientes/Miguel Díaz/Correos recibidos/Correo de Miguel.pdf',
    'Bomba Industrial/Contactos Proveedor/Proveedor B/Cotizacion Bomba Urgenta.pdf',
    'Bomba Industrial/Contactos Proveedor/Proveedor B/Pedidos/Ordenes Recientes/Orden de Compra 123.pdf',
    'Bomba Industrial/Descripcion General/Ficha Tecnica Bomba Industrial.pdf',
    'Bomba Industrial/Descripcion General/Operacion/Caudales/Máximos y Mínimos/Diagrama de Caudales.pdf',
    'Bomba Industrial/Especificaciones Tecnicas/ET Bomba RPM.pdf',
    'Bomba Industrial/Especificaciones Tecnicas/Rendimiento/Curvas/Detalle Oficial/Curva de Rendimiento.pdf',
    'Bomba Industrial/Fotos/Instalacion/Ubicación/Vista Principal/Foto Bomba Instalada.pdf',
    'Bomba Industrial/Fotos/Foto Vista Lateral.pdf',
    'Bomba Industrial/Manuales/Manual Instalacion Bomba.pdf',
    'Bomba Industrial/Manuales/Diagnostico/Fallas Comunes/Guia Rápida/Guia de Troubleshooting.pdf',
    'Bomba Industrial/Ofertas/Oferta Reemplazo Motor.pdf',
    'Bomba Industrial/Ofertas/Servicios/Mantenimiento/Propuesta 2024/Cotizacion Servicio Anual.pdf',
    'Bomba Industrial/Planos/Electrico/Conexionado/Esquema General/Plano Conexionado Electrico.pdf',
    'Bomba Industrial/Planos/Plano de Alineacion.pdf',
    'Bomba Industrial/Proveedores/Proveedor B/Datos Proveedor B.pdf',
    'Bomba Industrial/Proveedores/Proveedor B/Archivos/Contacto Principal/Tarjeta de Presentación.pdf',
    'Bomba Industrial/Proyectos/Sustitucion 2024/Planificacion/Control de Tiempos/Proyecto Sustitucion Bomba 2024.pdf',
    'Bomba Industrial/Proyectos/Plan de Mantenimiento.pdf',
    'Bomba Industrial/Reportes/Pruebas/Iniciales/Resumen de Valores/Reporte Pruebas Inicio Bomba.pdf',
    'Bomba Industrial/Reportes/Bitacora de Operacion.pdf',
    'Bomba Industrial/Repuestos/Impulsor/Planos/Piezas Internas/Impulsores/Plano Impulsor Bomba.pdf',
    'Bomba Industrial/Repuestos/Sello Mecánico/Especificaciones Tecnicas/Detalles/ET Sellos Mecanicos.pdf',
    'Bomba Industrial/Repuestos/Sello Mecánico/Especificaciones Tecnicas/Detalles/ET Sellos Mecanicos.pdf',
    'Bomba Industrial/Repuestos/Lubricante/Reportes/Hojas de Seguridad/Ficha Seguridad Lubricante.pdf',
    'Generador Eléctrico/Contactos Clientes/Miguel Marquez/Cédula.pdf',
    'Generador Eléctrico/Contactos Clientes/Miguel Marquez/RIF.pdf',
    'Generador Eléctrico/Contactos Clientes/Miguel Marquez/Facturas/Pagadas/Factura especial.pdf',
    'Generador Eléctrico/Contactos Clientes/Miguel Marquez/Correos recibidos/Archivados/Correo archivado de Miguel.pdf',
    'Generador Eléctrico/Contactos Clientes/Miguel Marquez/Correos recibidos/Correo de Miguel.pdf',
    'Generador Eléctrico/Contactos Clientes/Ana Vivas/Tambien.pdf',
    'Generador Eléctrico/Contactos Clientes/Ana Vivas/Diferencias.pdf',
    'Generador Eléctrico/Contactos Clientes/Ana Vivas/Facturas/Pagadas/Factura especial.pdf',
    'Generador Eléctrico/Contactos Clientes/Cliente Nuevo Generador/Datos.pdf',
    'Generador Eléctrico/Contactos Proveedor/Proveedor C/Cotizacion Alterna Gen.pdf',
    'Generador Eléctrico/Contactos Proveedor/Proveedor C/Acuerdos/Negociacion Final/Email Cierre.pdf',
    'Generador Eléctrico/Descripcion General/Ficha Tecnica Generador.pdf',
    'Generador Eléctrico/Descripcion General/Seguridad/Operacional/Documento Oficial/Manual de Seguridad Operacional.pdf',
    'Generador Eléctrico/Especificaciones Tecnicas/ET Generador Diesel 1000kVA.pdf',
    'Generador Eléctrico/Especificaciones Tecnicas/Eléctricas/Conexiones/Esquema/Diagrama Unifilar.pdf',
    'Generador Eléctrico/Fotos/Aereas/Ubicación/Vista Completa/Foto Generador Vista Aerea.pdf',
    'Generador Eléctrico/Fotos/Foto Panel Control.pdf',
    'Generador Eléctrico/Manuales/Manual Mantenimiento Motor.pdf',
    'Generador Eléctrico/Manuales/Sistema/Combustible/Guía de Uso/Manual Sistema de Combustible.pdf',
    'Generador Eléctrico/Ofertas/Oferta Instalacion 2024.pdf',
    'Generador Eléctrico/Ofertas/Garantia/Extension/Propuesta Cliente/Propuesta Extension de Garantia.pdf',
    'Generador Eléctrico/Planos/Control/Tablero/Final/Plano Tablero Control.pdf',
    'Generador Eléctrico/Planos/Plano Sistema de Enfriamiento.pdf',
    'Generador Eléctrico/Proveedores/Proveedor C/Datos Proveedor C.pdf',
    'Generador Eléctrico/Proveedores/Proveedor C/Archivos/Contacto Principal/Tarjeta de Presentación.pdf',
    'Generador Eléctrico/Proyectos/Respaldo Energia/Pruebas/Ejecución/Proyecto Respaldo Energia.pdf',
    'Generador Eléctrico/Proyectos/Cronograma de Pruebas.pdf',
    'Generador Eléctrico/Reportes/Consumo/Mensual/Lecturas Históricas/Reporte Consumo Mensual.pdf',
    'Generador Eléctrico/Reportes/Checklist Pre Operacional.pdf',
    'Generador Eléctrico/Repuestos/Alternador/Planos/Rotor/Plano Alternador Principal.pdf',
    'Generador Eléctrico/Repuestos/Alternador/Manuales/Reparación/Manual Repuesto Alternador.pdf',
    'Generador Eléctrico/Repuestos/Filtros Aceite/Fotos/Inspección/Foto Filtro Aceite.pdf',
    'Generador Eléctrico/Repuestos/Batería/Especificaciones Tecnicas/Auxiliar/ET Bateria Auxiliar.pdf',
    'Generador Eléctrico/Repuestos/Suministro Anual/Ofertas/Stock/Anual/Oferta Compra Stock Anual.pdf',
    'Generador Eléctrico/Repuestos/Suministro Anual/Reportes/Despacho/Trimestre 3/Reporte Despacho Repuestos Q3.pdf',
];
