<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\State;
use App\Models\City;

class CitySeeder extends Seeder
{
    public function run(): void
    {
        $states = State::all();

        $cities = [
            'Amazonas' => [
                'Puerto Ayacucho',
                'San Fernando de Atabapo',
                'La Esmeralda',
                'Maroa',
                'San Juan de Manapiare',
                'Puerto Páez',
                'Santa Rosa de Amanadona',
                'El Tigre',
                'San Carlos de Río Negro',
                'Tamatave',
            ],
            'Anzoátegui' => [
                'Barcelona',
                'Puerto La Cruz',
                'Lechería',
                'Guanta',
                'El Tigre',
                'Anaco',
                'Cantaura',
                'Pariaguán',
                'Puerto Píritu',
                'Clarines',
                'Boca de Uchire',
                'Aragua de Barcelona',
            ],
            'Apure' => [
                'San Fernando de Apure',
                'Guasdualito',
                'Achaguas',
                'Elorza',
                'Biruaca',
                'Mantecal',
                'Bruzuai',
                'Paso de Arauca',
                'San Juan de Payara',
                'Guarico',
                'San Rafael de Atamaica',
            ],
            'Aragua' => [
                'Maracay',
                'Turmero',
                'La Victoria',
                'Cagua',
                'El Limón',
                'Colonia Tovar',
                'Ocumare de la Costa',
                'San Mateo',
                'Villa de Cura',
                'Palo Negro',
                'Santa Cruz de Aragua',
                'Las Tejerías',
            ],
            'Barinas' => [
                'Barinas',
                'Socopó',
                'Santa Bárbara de Barinas',
                'Sabaneta',
                'Ciudad Bolivia',
                'Barrancas',
                'Obispos',
                'El Cantón',
                'Pedraza',
                'Barinitas',
                'Libertad',
            ],
            'Bolívar' => [
                'Ciudad Bolívar',
                'Ciudad Guayana (Puerto Ordaz y San Félix)',
                'Upata',
                'Caicara del Orinoco',
                'El Callao',
                'Santa Elena de Uairén',
                'Tumeremo',
                'Guasipati',
                'Maripa',
                'La Paragua',
                'El Dorado',
                'San Pedro de Las Bocas',
            ],
            'Carabobo' => [
                'Valencia',
                'Puerto Cabello',
                'Guacara',
                'Tocuyito',
                'Mariara',
                'Morón',
                'San Joaquín',
                'Bejuma',
                'Miranda',
                'Montalbán',
                'Los Guayos',
                'Campo de Carabobo',
            ],
            'Cojedes' => [
                'San Carlos',
                'Tinaquillo',
                'El Baúl',
                'Tinaco',
                'Las Vegas',
                'Libertad de Cojedes',
                'Macapo',
                'San Antonio de Padua',
                'La Aguadita',
                'Apartaderos',
            ],
            'Delta Amacuro' => [
                'Tucupita',
                'Pedernales',
                'Sierra Imataca',
                'Capure',
                'San José de Tucupita',
                'Boca de Macareo',
                'Curiapo',
                'El Triunfo',
                'La Horqueta',
                'Los Castillos',
            ],
            'Distrito Capital' => [
                'Caracas (Centro)',
                'El Hatillo',
                'Baruta',
                'Chacao',
                'Sucre (Petare)',
                'Coche',
                'El Valle',
                'La Pastora',
                'San Bernardino',
                'Santa Rosalía',
                'Macarao',
                'Antímano',
            ],
            'Falcón' => [
                'Coro',
                'Punto Fijo',
                'Pueblo Nuevo',
                'Chichiriviche',
                'Tucacas',
                'Dabajuro',
                'Pedregal',
                'Mirimire',
                'San Luis',
                'Tocópero',
                'Adícora',
                'Puerto Cumarebo',
            ],
            'Guárico' => [
                'San Juan de los Morros',
                'Calabozo',
                'Valle de la Pascua',
                'Altagracia de Orituco',
                'Camaguán',
                'Tucupido',
                'Zaraza',
                'Las Mercedes',
                'El Socorro',
                'Ortiz',
                'Guayabal',
                'Mellado',
            ],
            'La Guaira (Vargas)' => [
                'La Guaira',
                'Maiquetía',
                'Catia La Mar',
                'Caraballeda',
                'Macuto',
                'Naiguatá',
                'Carayaca',
                'La Soublette',
                'El Junko',
                'Tanaguarena',
            ],
            'Lara' => [
                'Barquisimeto',
                'Carora',
                'Cabudare',
                'El Tocuyo',
                'Quíbor',
                'Duaca',
                'Sarare',
                'Siquisique',
                'Cubiro',
                'Sanare',
                'Aguada Grande',
                'Río Claro',
            ],
            'Mérida' => [
                'Mérida',
                'El Vigía',
                'Tovar',
                'Ejido',
                'Santa Cruz de Mora',
                'Guaraque',
                'Mucuchíes',
                'Santo Domingo',
                'Arapuey',
                'Timotes',
                'La Azulita',
                'Lagunillas',
            ],
            'Miranda' => [
                'Los Teques',
                'Guarenas',
                'Guatire',
                'Ocumare del Tuy',
                'Cúa',
                'Santa Lucía',
                'Charallave',
                'Higuerote',
                'Río Chico',
                'Petare (parte del Área Metropolitana)',
                'San Antonio de los Altos',
                'Santa Teresa del Tuy',
            ],
            'Monagas' => [
                'Maturín',
                'Punta de Mata',
                'Caripito',
                'Temblador',
                'Caripe',
                'Teresén',
                'Aragua de Maturín',
                'Aguasay',
                'Barrancas',
                'Chaguaramas',
                'Jusepín',
                'El Furrial',
            ],
            'Nueva Esparta' => [
                'La Asunción',
                'Porlamar',
                'Pampatar',
                'Juan Griego',
                'El Valle del Espíritu Santo',
                'San Juan Bautista',
                'Boca del Río',
                'Villa Rosa',
                'Tucupita (en Margarita)',
                'Pedregales',
                'Punta de Piedras',
                'Las Guevaras',
            ],
            'Portuguesa' => [
                'Guanare',
                'Acarigua',
                'Araure',
                'Ospino',
                'Biscucuy',
                'Villa Bruzual',
                'Píritu',
                'San Rafael de Onoto',
                'Papelón',
                'Turén',
                'Santa Rosalía',
                'Chabasquén',
            ],
            'Sucre' => [
                'Cumaná',
                'Carúpano',
                'Güiria',
                'Río Caribe',
                'Cariaco',
                'Yaguaraparo',
                'El Pilar',
                'San Antonio del Golfo',
                'Casana',
                'Irapa',
                'Marigüitar',
                'Araya',
            ],
            'Táchira' => [
                'San Cristóbal',
                'Táriba',
                'Rubio',
                'La Grita',
                'San Antonio del Táchira',
                'Capacho Nuevo',
                'Coloncito',
                'Lobatera',
                'Punto Fijo (del Táchira)',
                'San Josecito',
                'El Piñal',
                'Cordero',
            ],
            'Trujillo' => [
                'Trujillo',
                'Valera',
                'Boconó',
                'Escuque',
                'Betijoque',
                'Carache',
                'Monay',
                'Santa Ana de Trujillo',
                'Pampán',
                'Isnotú',
                'Chejendé',
                'Motatán',
            ],
            'Yaracuy' => [
                'San Felipe',
                'Yaritagua',
                'Chivacoa',
                'Cocorote',
                'Nirgua',
                'Aroa',
                'Urachiche',
                'Guama',
                'Sabana de Parra',
                'Albarico',
                'Boraure',
                'El Guayabo',
            ],
            'Zulia' => [
                'Maracaibo',
                'Cabimas',
                'Ciudad Ojeda',
                'Machiques',
                'San Carlos del Zulia',
                'Santa Rita',
                'Los Puertos de Altagracia',
                'Villa del Rosario',
                'La Concepción',
                'Bobures',
                'El Moján',
                'Bachaquero',
            ],
        ];

        foreach ($states as $state) {
            $nested = $cities[$state->name];

            foreach ($nested as $city) {
                City::create([
                    'name' => $city,
                    'state_id' => $state->id,
                ]);
            }
        }

    }
}
