<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $date = now()->subDay();
        $date = now()->subHour();

        $countries = [
            ['name' => 'Venezuela', 'created_at' => $date, 'updated_at' => $date],
            ['name' => 'China'],
            ['name' => 'Estados Unidos'],
            ['name' => 'Argentina'],
            ['name' => 'Canadá'],
            ['name' => 'Chile'],
            ['name' => 'Bolivia'],
            ['name' => 'Brasil'],
            ['name' => 'Colombia'],
            ['name' => 'Ecuador'],
            ['name' => 'España'],
            ['name' => 'México'],
            ['name' => 'Paraguay'],
            ['name' => 'Perú'],
            ['name' => 'Arabia Saudita'],

            ['name' => 'Afganistán'],
            ['name' => 'Albania'],
            ['name' => 'Alemania'],
            ['name' => 'Andorra'],
            ['name' => 'Angola'],
            ['name' => 'Antigua y Barbuda'],
            ['name' => 'Argelia'],
            ['name' => 'Armenia'],
            ['name' => 'Australia'],
            ['name' => 'Austria'],
            ['name' => 'Azerbaiyán'],
            ['name' => 'Bahamas'],
            ['name' => 'Baréin'],
            ['name' => 'Bangladés'],
            ['name' => 'Barbados'],
            ['name' => 'Bielorrusia'],
            ['name' => 'Bélgica'],
            ['name' => 'Belice'],
            ['name' => 'Benín'],
            ['name' => 'Bután'],
            ['name' => 'Bosnia y Herzegovina'],
            ['name' => 'Botsuana'],
            ['name' => 'Brunéi'],
            ['name' => 'Bulgaria'],
            ['name' => 'Burkina Faso'],
            ['name' => 'Burundi'],
            ['name' => 'Cabo Verde'],
            ['name' => 'Camboya'],
            ['name' => 'Camerún'],
            ['name' => 'Catar'],
            ['name' => 'Chad'],
            ['name' => 'Chipre'],
            ['name' => 'Ciudad del Vaticano (Santa Sede)'],
            ['name' => 'Comoras'],
            ['name' => 'Congo (Brazzaville)'],
            ['name' => 'Congo (Kinshasa)'],
            ['name' => 'Corea del Norte'],
            ['name' => 'Corea del Sur'],
            ['name' => 'Costa de Marfil'],
            ['name' => 'Costa Rica'],
            ['name' => 'Croacia'],
            ['name' => 'Cuba'],
            ['name' => 'Dinamarca'],
            ['name' => 'Dominica'],
            ['name' => 'Egipto'],
            ['name' => 'El Salvador'],
            ['name' => 'Emiratos Árabes Unidos'],
            ['name' => 'Eritrea'],
            ['name' => 'Eslovaquia'],
            ['name' => 'Eslovenia'],
            ['name' => 'Estonia'],
            ['name' => 'Etiopía'],
            ['name' => 'Filipinas'],
            ['name' => 'Finlandia'],
            ['name' => 'Fiyi'],
            ['name' => 'Francia'],
            ['name' => 'Gabón'],
            ['name' => 'Gambia'],
            ['name' => 'Georgia'],
            ['name' => 'Ghana'],
            ['name' => 'Granada'],
            ['name' => 'Grecia'],
            ['name' => 'Guatemala'],
            ['name' => 'Guinea'],
            ['name' => 'Guinea-Bisáu'],
            ['name' => 'Guinea Ecuatorial'],
            ['name' => 'Guyana'],
            ['name' => 'Haití'],
            ['name' => 'Honduras'],
            ['name' => 'Hungría'],
            ['name' => 'India'],
            ['name' => 'Indonesia'],
            ['name' => 'Irak'],
            ['name' => 'Irán'],
            ['name' => 'Irlanda'],
            ['name' => 'Islandia'],
            ['name' => 'Islas Marshall'],
            ['name' => 'Islas Salomón'],
            ['name' => 'Israel'],
            ['name' => 'Italia'],
            ['name' => 'Jamaica'],
            ['name' => 'Japón'],
            ['name' => 'Jordania'],
            ['name' => 'Kazajistán'],
            ['name' => 'Kenia'],
            ['name' => 'Kirguistán'],
            ['name' => 'Kiribati'],
            ['name' => 'Kuwait'],
            ['name' => 'Laos'],
            ['name' => 'Lesoto'],
            ['name' => 'Letonia'],
            ['name' => 'Líbano'],
            ['name' => 'Liberia'],
            ['name' => 'Libia'],
            ['name' => 'Liechtenstein'],
            ['name' => 'Lituania'],
            ['name' => 'Luxemburgo'],
            ['name' => 'Madagascar'],
            ['name' => 'Malasia'],
            ['name' => 'Malaui'],
            ['name' => 'Maldivas'],
            ['name' => 'Malí'],
            ['name' => 'Malta'],
            ['name' => 'Marruecos'],
            ['name' => 'Mauricio'],
            ['name' => 'Mauritania'],
            ['name' => 'Micronesia'],
            ['name' => 'Moldavia'],
            ['name' => 'Mónaco'],
            ['name' => 'Mongolia'],
            ['name' => 'Montenegro'],
            ['name' => 'Mozambique'],
            ['name' => 'Myanmar (Birmania)'],
            ['name' => 'Namibia'],
            ['name' => 'Nauru'],
            ['name' => 'Nepal'],
            ['name' => 'Nicaragua'],
            ['name' => 'Níger'],
            ['name' => 'Nigeria'],
            ['name' => 'Noruega'],
            ['name' => 'Nueva Zelanda'],
            ['name' => 'Omán'],
            ['name' => 'Países Bajos'],
            ['name' => 'Pakistán'],
            ['name' => 'Palaos'],
            ['name' => 'Palestina'],
            ['name' => 'Panamá'],
            ['name' => 'Papúa Nueva Guinea'],
            ['name' => 'Polonia'],
            ['name' => 'Portugal'],
            ['name' => 'Reino Unido'],
            ['name' => 'República Centroafricana'],
            ['name' => 'República Checa'],
            ['name' => 'República Dominicana'],
            ['name' => 'Macedonia del Norte'],
            ['name' => 'Ruanda'],
            ['name' => 'Rumania'],
            ['name' => 'Rusia'],
            ['name' => 'Samoa'],
            ['name' => 'San Cristóbal y Nieves'],
            ['name' => 'San Marino'],
            ['name' => 'San Vicente y las Granadinas'],
            ['name' => 'Santa Lucía'],
            ['name' => 'Santo Tomé y Príncipe'],
            ['name' => 'Senegal'],
            ['name' => 'Serbia'],
            ['name' => 'Seychelles'],
            ['name' => 'Sierra Leona'],
            ['name' => 'Singapur'],
            ['name' => 'Siria'],
            ['name' => 'Somalia'],
            ['name' => 'Sri Lanka'],
            ['name' => 'Sudáfrica'],
            ['name' => 'Sudán'],
            ['name' => 'Sudán del Sur'],
            ['name' => 'Suecia'],
            ['name' => 'Suiza'],
            ['name' => 'Surinam'],
            ['name' => 'Tailandia'],
            ['name' => 'Tanzania'],
            ['name' => 'Tayikistán'],
            ['name' => 'Timor Oriental'],
            ['name' => 'Togo'],
            ['name' => 'Tonga'],
            ['name' => 'Trinidad y Tobago'],
            ['name' => 'Túnez'],
            ['name' => 'Turkmenistán'],
            ['name' => 'Turquía'],
            ['name' => 'Tuvalu'],
            ['name' => 'Ucrania'],
            ['name' => 'Uganda'],
            ['name' => 'Uruguay'],
            ['name' => 'Uzbekistán'],
            ['name' => 'Vanuatu'],
            ['name' => 'Vietnam'],
            ['name' => 'Yemen'],
            ['name' => 'Yibuti'],
            ['name' => 'Zambia'],
            ['name' => 'Zimbabue'],
        ];

        foreach ($countries as $country) {
            Country::create($country);
        }
    }
}
